UserManager/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JNPPortal.Models
{
    public class Driver
    {
        public int ID { get; set; }

        [StringLength(50)]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [StringLength(50)]
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [StringLength(50)]
        [DisplayName("Super Shuttle Id")]
        public string SuperShuttleID { get; set; }

        [DisplayName("Default Van")]
        public Nullable<int> DefaultVanId { get; set; }
        [DisplayName("Default Van")]
        public string DefaultVan { get; set; }

        [DisplayName("Driver Share 1")]
        public Nullable<decimal> DriverShare1 { get; set; }
        [DisplayName("Driver Share 2")]
        public Nullable<decimal> DriverShare2 { get; set; }

        public string DisplayName
        {
            get { return FirstName + " " + LastName + " - " + SuperShuttleID; }
        }

    }
}

UserManager/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using JNPPortal.Models;

namespace JNPPortal.Controllers
{
    public class DriversController : Controller
    {
        // GET: Drivers
        public ActionResult Index()
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("api/drivers").Result;
            IEnumerable<Driver> drivers = response.Content.ReadAsAsync<IEnumerable<Driver>>().Result;

            return View(drivers.ToList());
            
        }

        

       
        // GET: Drivers/AddOrEdit/5
        public ActionResult AddOrEdit(int id=0)
        {

            //Get Van list
            HttpResponseMessage responseVans = GlobalVariables.WebApiClient.GetAsync("api/Vans").Result;
            IEnumerable<Van> vans = responseVans.Content.ReadAsAsync<IEnumerable<Van>>().Result;
            ViewBag.VanList = new SelectList(vans, "Id", "Name", "Select One");

            if (id == 0)
            {
                ViewBag.Title = "Create new Driver";
                ViewBag.New = true;                

                //New user
                Driver driver = new Driver();
                driver.DriverShare1 = Convert.ToDecimal(.8);
                driver.DriverShare2 = Convert.ToDecimal(.5);

                return View(driver);
            }
            else
            {
                //Get Driver details
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("api/Drivers/" + id.ToString()).Result;
                Driver driver = response.Content.ReadAsAsync<Driver>().Result;

                ViewBag.Title = "Driver - " + driver.FirstName + " " + driver.LastName;
                ViewBag.New = false;

                return View(driver);
            }          
        }


        [HttpPost]
        // GET: Drivers/AddOrEdit/5
        public ActionResult AddOrEdit(Driver driver)
        {

            if (!ModelState.IsValid)
            {
                return View(driver);

            }

            //Get Van list
            HttpResponseMessage responseVans = GlobalVariables.WebApiClient.GetAsync("api/Vans").Result;
            IEnumerable<Van> vans = responseVans.Content.ReadAsAsync<IEnumerable<Van>>().Result;
            ViewBag.VanList = new SelectList(vans, "Id", "Name", "Select One");


            //Save changes      
            if (driver.ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("api/Drivers", driver).Result;
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("api/Drivers/", driver).Result;
            }

            //Message to display                                
            if (driver.ID == 0)
            {
                TempData["SuccessMessage"] = "Driver created Successfully";
            }
            else
            {
                TempData["SuccessMessage"] = "Driver updated Successfully";
            }

            return View(driver);
        }


        // GET: Drivers/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Drivers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET Drivers/GetGrid
        public ActionResult GetGrid()
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("api/drivers").Result;
            IEnumerable<Driver> drivers = response.Content.ReadAsAsync<IEnumerable<Driver>>().Result;

            return Json(new { data = drivers }, JsonRequestBehavior.AllowGet);
        }
    }
}

UserManager/Views/Drivers/AddOrEdit.cshtml
@model JNPPortal.Models.Driver

@{

    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
<script src="~/Content/TextEditor/jquery-te-1.4.0.min.js"></script>
<link href="~/Content/TextEditor/jquery-te-1.4.0.css" rel="stylesheet" />
<script>
    $('.ckeditor').jqte();
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-solid box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Edit User</h3>
                    </div><!-- /.box-header -->

                    <div class="alert alert-success alert-dismissable" id="dvMsgUser" style="display:none;">
                        <i class="fa fa-apple"></i>
                        <b> Update Successfully. </b>
                    </div>
                    <!-- form start -->

                    <div role="form">
                        <div class="box-body">


                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName, new { @class = "" })
                                @Html.EditorFor(model => model.FirstName)
                                @Html.ValidationMessageFor(model => model.FirstName)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, new { @class = "" })
                                @Html.EditorFor(model => model.LastName)
                                @Html.ValidationMessageFor(model => model.LastName)
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.SuperShuttleID, new { @class = "" })
                                @Html.EditorFor(model => model.SuperShuttleID)
                                @Html.ValidationMessageFor(model => model.SuperShuttleID)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DefaultVanId, new { @class = "" })
                                @Html.DropDownListFor(model => model.DefaultVanId, (SelectList)ViewBag.VanList, "Select One", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DefaultVanId)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.DriverShare1, new { @class = "" })
                                @Html.EditorFor(model => model.DriverShare1)
                                @Html.ValidationMessageFor(model => model.DriverShare1)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DriverShare2, new { @class = "" })
                                @Html.EditorFor(model => model.DriverShare2)
                                @Html.ValidationMessageFor(model => model.DriverShare2)
                            </div>

                            <div class="box-footer">


                                @*History Back*@
                                @if (Request.UrlReferrer != null)
                                {
                                    <div class="col-md-1">
                                        <a href=@Request.UrlReferrer class="btn btn-primary">
                                            <i class="fa fa-home">
                                                Back
                                            </i>
                                        </a>
                                    </div>
                                }

                                <input type="submit" name="submit" value="Save" class="btn btn-primary" />

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

}


<script>
    $(function () {
        $("#roles-multiselect").chosen();
        width: "100%"

    });
</script>

UserManager/Views/Drivers/Index.cshtml
@model IEnumerable<JNPPortal.Models.Driver>

@{
    ViewBag.Title = "Driver List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section ScriptsOrCss
{

    <link href="~/Content/DataTable/new/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Content/DataTable/new/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/Content/DataTable/new/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="~/Content/DataTable/new/jszip.min.js" type="text/javascript"></script>
    <script src="~/Content/DataTable/new/pdfmake.min.js" type="text/javascript"></script>
    <script src="~/Content/DataTable/new/vfs_fonts.js" type="text/javascript"></script>
    <script src="~/Content/DataTable/new/buttons.html5.min.js" type="text/javascript"></script>
    <link href="~/Content/DataTable/new/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/DataTable/new/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />

}
<section class="content-header">
    <h1>
        @ViewBag.Title
        <small> @ViewBag.Title</small>
    </h1>
</section>

<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-solid box-primary">

                <div class="box-body">
                    <!-- Split button -->
                    <div class="margin">

                        <div class="btn-group">
                            <a href="@Url.Action("AddorEdit","Drivers")" class="btn btn-primary">Create</a>
                        </div>
                    </div>
                    <!-- flat split buttons -->
                </div><!-- /.box-body -->
            </div>
            <div class="box box-solid box-primary">
                <div class="box-header">
                    <h3 class="box-title">@ViewBag.Title</h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive">

                    <div class="margin">

                        <div class="streaming-table">
                            <span id="found" class="label label-info"></span>


                            <table id="tblDriver" class="display nowrap">
                                <thead>
                                    <tr>
                                        <th> No. </th>
                                        <th> @Html.DisplayNameFor(model => model.FirstName) </th>
                                        <th> @Html.DisplayNameFor(model => model.LastName) </th>
                                        <th> @Html.DisplayNameFor(model => model.SuperShuttleID) </th>
                                        <th> @Html.DisplayNameFor(model => model.DefaultVan) </th>
                                        <th> @Html.DisplayNameFor(model => model.DriverShare1) </th>
                                        <th> @Html.DisplayNameFor(model => model.DriverShare2) </th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>

                            <div id="summary">
                                <div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box box-solid box-primary">

                <div class="box-body">
                    <!-- Split button -->
                    <div class="margin">

                        <div class="btn-group">
                            <a href="@Url.Action("AddorEdit","Drivers")" class="btn btn-primary">Create</a>
                        </div>
                    </div>
                    <!-- flat split buttons -->
                </div><!-- /.box-body -->
            </div>
        </div>
    </div>
</section>


<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
<script type="text/javascript">


        
         $(document).ready(function () {


        $("#tblDriver").dataTable(

            {
                "ajax": {

                    "url": "/Drivers/GetGrid",
                    "type": "GET",
                    "dataType": "json"
                },

                "columns": [
                    {
                        "data": "ID", "render": function  (data)
                        {
                            return "<a href = '@Url.Action("AddorEdit","Drivers")/" + data + "')>" + data + "</a>";
                        },

                    },
                 
                    {
                        "data": "FirstName", "render": function (data, type, row)
                        {
                            return "<a href = '@Url.Action("AddorEdit","Drivers")/" + row['ID'] + "')>" + data + "</a>";
                        },
                    },
                    {
                        "data": "LastName", "render": function (data, type, row)
                        {
                               return "<a href = '@Url.Action("AddorEdit","Drivers")/" + row['ID'] + "')>" + data + "</a>";
                        },
                    },

                    {
                        "data": "SuperShuttleID", "render": function (data,type,row)
                        {
                            return "<a href = '@Url.Action("AddorEdit","Drivers")/" + row['ID'] + "')>" + data + "</a>";
                        },
                    },
                    {
                        "data": "DefaultVan", "render": function (data, type, row)
                        {
                               return "<a href = '@Url.Action("AddorEdit","Drivers")/" + row['ID'] + "')>" + data + "</a>";
                        },
                    },
                    {
                        "data": "DriverShare1", "render": function (data, type, row)
                        {
                               return "<a href = '@Url.Action("AddorEdit","Drivers")/" + row['ID'] + "')>" + data + "</a>";
                        },
                    },
                    {
                        "data": "DriverShare2", "render": function (data, type, row)
                        {
                               return "<a href = '@Url.Action("AddorEdit","Drivers")/" + row['ID'] + "')>" + data + "</a>";
                        },
                    },

                ],
                "dom": "Bfrtip",
                "buttons": ['copy', 'pdf', 'excel', 'csv'],


            });
         });



</script>